# Generated by Django 6.0.1 on 2026-01-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=45)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.lectures')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=35)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Age', models.IntegerField()),
                ('Nationality', models.TextField(blank=True, null=True)),
                ('courses', models.ManyToManyField(to='university.courses')),
            ],
        ),
    ]
